import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { Footer } from "./components/app-footer";
import { Header } from "./components/app-header";
import { AppSidebar } from "./components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <SidebarProvider>
          <div className="min-h-screen bg-gray-50 w-full">
            <div className="flex">
              <AppSidebar />
              <SidebarInset className="flex min-h-screen w-full flex-col">
                {/* Header */}
                <Header />

                {/* Main Content */}
                <main>{children}</main>
                {/* Footer */}
                <Footer />
              </SidebarInset>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
